import { z } from "zod";
import { IdSchema, IsoDateTimeSchema } from "./common";
import { EnrollmentStatusSchema, GapSeveritySchema } from "./enums";

/** One step in a generated pathway. */
export const PathwayMilestoneSchema = z.object({
  id: IdSchema,
  order: z.number().int().nonnegative(),
  kind: z.enum(["course", "programme", "assessment", "lab", "certificate"]),
  refId: IdSchema.describe("Id of the course/programme/assessment this milestone points at"),
  title: z.string(),
  estimatedMinutes: z.number().int().nonnegative(),
  status: z.enum(["locked", "available", "in_progress", "completed", "skipped"]),
  /** Competency keys this milestone advances. */
  competencyKeys: z.array(z.string()),
});
export type PathwayMilestone = z.infer<typeof PathwayMilestoneSchema>;

/** A personalised, ordered plan generated by the recommendation engine. */
export const LearningPathSchema = z.object({
  id: IdSchema,
  userId: IdSchema,
  title: z.string(),
  rationale: z.string().describe("Why this path was generated, in plain language"),
  targetCompetencyKeys: z.array(z.string()),
  milestones: z.array(PathwayMilestoneSchema),
  progressPercent: z.number().min(0).max(100),
  totalEstimatedMinutes: z.number().int().nonnegative(),
  estimatedCompletionAt: IsoDateTimeSchema.nullable(),
  createdAt: IsoDateTimeSchema,
  updatedAt: IsoDateTimeSchema,
});
export type LearningPath = z.infer<typeof LearningPathSchema>;

/**
 * A single ranked suggestion surfaced on the dashboard.
 * `reasonCodes` must be machine-stable; `reasons` is the display text.
 */
export const RecommendationSchema = z.object({
  id: IdSchema,
  kind: z.enum(["course", "programme", "assessment", "path"]),
  refId: IdSchema,
  title: z.string(),
  summary: z.string(),
  matchScore: z.number().min(0).max(100),
  reasonCodes: z.array(
    z.enum([
      "closes_critical_gap",
      "role_requirement",
      "department_priority",
      "career_progression",
      "emerging_technology",
      "peers_completed",
      "continues_path",
      "low_confidence_needs_assessment",
    ]),
  ),
  reasons: z.array(z.string()),
  competencyKeys: z.array(z.string()),
  severity: GapSeveritySchema.nullable(),
});
export type Recommendation = z.infer<typeof RecommendationSchema>;

/** A user's relationship to one course or programme. */
export const EnrollmentSchema = z.object({
  id: IdSchema,
  userId: IdSchema,
  kind: z.enum(["course", "programme"]),
  refId: IdSchema,
  title: z.string(),
  thumbnailUrl: z.string().url().nullable(),
  status: EnrollmentStatusSchema,
  progressPercent: z.number().min(0).max(100),
  /** Module id to resume at; null when not started or completed. */
  resumeModuleId: IdSchema.nullable(),
  minutesSpent: z.number().int().nonnegative(),
  isBookmarked: z.boolean(),
  enrolledAt: IsoDateTimeSchema,
  completedAt: IsoDateTimeSchema.nullable(),
  dueAt: IsoDateTimeSchema.nullable(),
});
export type Enrollment = z.infer<typeof EnrollmentSchema>;

export const CertificateSchema = z.object({
  id: IdSchema,
  userId: IdSchema,
  title: z.string(),
  issuedBy: z.string(),
  issuedAt: IsoDateTimeSchema,
  /** Public code for third-party verification. */
  verificationCode: z.string(),
  competencyKeys: z.array(z.string()),
  downloadUrl: z.string().url().nullable(),
});
export type Certificate = z.infer<typeof CertificateSchema>;

/** Aggregates for the employee dashboard header. */
export const LearningStatsSchema = z.object({
  userId: IdSchema,
  hoursThisWeek: z.number().nonnegative(),
  hoursThisMonth: z.number().nonnegative(),
  hoursTotal: z.number().nonnegative(),
  streakDays: z.number().int().nonnegative(),
  coursesCompleted: z.number().int().nonnegative(),
  coursesInProgress: z.number().int().nonnegative(),
  certificatesEarned: z.number().int().nonnegative(),
  competencyPointsGained: z.number().nonnegative().describe("Level increase summed, last 90 days"),
});
export type LearningStats = z.infer<typeof LearningStatsSchema>;
